### ISSUE TITLE
Signify when user is typing into EditableButtons

### ISSUE THREAD

**Issue by git12121** [aiyayayaya/canny-capybaras-collab-code-contest#11]
Like this cursor icon:
![image](https://user-images.githubusercontent.com/28541089/125611897-18972cd1-63bd-4488-9781-21a34d31023d.png)

**Comment by EarthKiii** [comment]
idk if thats what you need ? : 
https://docs.python.org/3/library/curses.html#curses.curs_set

**Comment by EarthKiii** [comment]
else i found this :
https://docs.python.org/3/howto/curses.html#attributes-and-color

**Comment by git12121** [comment]
> idk if thats what you need ? :
> https://docs.python.org/3/library/curses.html#curses.curs_set

I'm not sure how we could set the position of that to the EditableButton's position

**Comment by git12121** [comment]
> else i found this :
> https://docs.python.org/3/howto/curses.html#attributes-and-color

This looks like it could work

**Comment by git12121** [comment]
I'll give it a shot after I finish #9

**Comment by git12121** [comment]
I just checked I don't think there's an attribute that gives us the effect we want. `curs_set(1)` does work but it stays in the bottom right corner of the screen and I'm not sure how to change that

**Comment by redish2098** [comment]
i had the same problem, i do have an idea though which ill post in discord when im done
