### ISSUE TITLE
Comic ID Input

### ISSUE THREAD

**Issue by git12121** [aiyayayaya/canny-capybaras-collab-code-contest#4]
![image](https://user-images.githubusercontent.com/28541089/125335978-133dd500-e345-11eb-9b08-2843ba73b83d.png)

The red text should be editable (by clicking it and typing).

This should work in a similar way to how MS Word handles choosing which pages to print:
![image](https://user-images.githubusercontent.com/28541089/125336056-32d4fd80-e345-11eb-8c1c-22a8dfe7c090.png)

For example:
`60` would get comic ID 60
`60, 70` would get comic ID 60 and 70
`60-70` would get comic ID 60 through to 70 (60, 61, 62, 63...)
`60, 65-68, 70` would get comic ID 60, 65, 66, 67, 68, and 70

There should also be leeway in terms of what input is considered valid. For example:
`60 70` should be the same as `60, 70`

**Comment by mariothedog** [comment]
Reserving this
